//===================
// Import
//===================
import { emit, eventBus, events } from '../eventBus.js';
import { log } from '../utils.js';
import { filter } from 'rxjs/operators';



//===================
// Functions
//===================
export class analyzeHTTP {
  constructor() {
    this.generatedEndpoints = new Set();
  }

  init() {
    eventBus
      .pipe(filter(e => e.type === events.GEN_HTTP_EVENT_FLAG))
      .subscribe(e => this.generatedEndpoints.add(e.payload));
  }



  parseHTTP({ type, request, response }) {
    if (!response || !request) { return; }

    const uri = this.getURI(request?.uri)
    if (!uri) { return; }

    const protocol = uri.protocol;
    const port = uri.port;
    const rawQueries = uri.search; // ?page=1order=asc...
    const params = this.searchParamsToObj(uri.searchParams); // { page:1,order:'asc' }
    const hostname = uri.hostname;
    const fullPath = decodeURIComponent(uri.pathname); // path name can be encoded
    const segments = fullPath.split('/').filter(Boolean);

    const meta = {
      protocol,
      port,
      rawQueries,
      params,
      hostname,
      path: { fullPath, segments },
      isGenerated: false,
    }

    // flag requests generated by the browser extension to avoid regular analysis
    if (this.generatedEndpoints.has(request?.uri)) {
      meta.isGenerated = true;
      log({module: 'http analyzer', msg: `intercepted and flagged a generated HTTP event`});
    }

    emit({
      type: events.HTTP_EVENT, payload: {
        type,
        request: { ...request, meta },
        response,
        done: meta.isGenerated, // skip analysis
      }
    });
  }



  getURI(uri) {
    if (!uri) { return; }

    try {
      return new URL(uri, window?.location?.origin);
    } catch (e) {
      return;
    }
  }



  searchParamsToObj(searchParams) {
    const paramsMap = Array.from(searchParams).reduce((params, [key, val]) => params.set(key, val), new Map());
    return Object.fromEntries(paramsMap);
  }
}